apiVersion: v1
kind: Service
metadata:
  name: partner
  labels:
    name: partner
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: partner